
language: swift

osx_image: xcode10.2

branches:
 only:
 - master

cache: 
  - bundler

env:
  global:
    - WORKSPACE=Resolver.xcworkspace
    - COVERALLS_SERVICE_NAME=travis-ci
    - COVERALLS_SERVICE_JOB_ID=$TRAVIS_JOB_ID

install:
  - bundle install --without=documentation

script:
  - swift build
  - swift test
  
after_success:
  - slather
