
language: swift

osx_image: xcode10.2

branches:
 only:
 - master

cache: 
  - bundler

env:
  global:
    - WORKSPACE=Resolver.xcworkspace
    - COVERALLS_SERVICE_NAME=travis-ci
    - COVERALLS_SERVICE_JOB_ID=$TRAVIS_JOB_ID
  matrix:
    - DESTINATION="OS=12.2,name=iPhone 8" SCHEME="Resolver" SDK="iphonesimulator10.0" RUN_TESTS="YES"

install:
  - bundle install --without=documentation
  - swift package update

script:
  - swift build
  - swift test
  
after_success:
  - slather
